### PR TITLE
fix: send information on error

### PR DESCRIPTION
**Pull request by simone-sanfratello**
See issue https://github.com/fastify/github-action-merge-dependabot/issues/28

The error message will be

automerge error

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by simoneb — COMMENTED** [review]
I'm not a great fan of code structured in this way where all variables are defined as mutable upfront. 

I would suggest an alternative implementation that requires less changes and preserves the original error message which is the response we're getting from GitHub when something goes wrong. 

That way we could simply enrich the error by linking to the docs and you can leave most of the code unchanged and only change server.js to catch an error and return an error response which contains a link to the usage docs but also preserves the original GH error.

WDYT?

**Comment by simone-sanfratello** [comment]
The origin of the issue was that the function `getRepositoryInstallation` in `github.js` was throwing an error.
So try/catch blocks in `server.js` are needed in order to throw to the upper level the specific error from github requests, so the structure of the code. An alternative could be to move try/catch block inside github functions, but without one of these solutions, [this error](https://github.com/fastify/dependabot-merge-action-app/pull/14/files#diff-9660787b66210e646b3ca8b6e23c097b27a1528d472936955407a61e7834c42cL33) can't be thrown.

We could throw straight the github error message to the server response, but in this case we are removing the information of the context of the error.

**Comment by simoneb** [comment]
I understand what you mean and while I agree that the way the github.js file does things is not necessarily idea. It always asserts on a successful status code of the response and uses the response body as the assertion message, which allows preserving the original error. 
Nevertheless, unless we want to change how that works, I think the same benefit of your current solution can be achieved by simply not changing anything in approveAndMerge.js and instead try/catch in server.js, decorating the error with a link to the docs.

Wouldn't that provide the same level of information that your current change?

**Comment by simone-sanfratello** [comment]
This is probably the solution you are saying

https://github.com/fastify/dependabot-merge-action-app/compare/fix/error-message-second-28

Note I removed the `throw Error` on `approveAndMerge.js` because they are not reached in case of a not-ok response from github

And the final error will be - that contains "Integration not found"

```
Error: Request failed with status code 400: {"statusCode":400,"error":"Bad Request","message":"{\"message\":\"Integration not found\",\"documentation_url\":\"https://docs.github.com/rest\"} - see https://github.com/fastify/github-action-merge-dependabot#usage"}
``

**Comment by simoneb** [comment]
Yes! I think it's easier and conveys the meaning. I would put the link to the docs before, and then append the original error details later.

**Pull request closed without merging**
